language: nix

install:
  - cat /etc/nix/nix.conf > ~/nix.conf
  - echo "binary-caches = https://cache.nixos.org https://hydra.angeldsis.com" > ~/nix.conf
  - export NIX_CONF_DIR=~
  - cat ~/nix.conf

script:
 - nix-build --arg tests true --arg haddock true
